### ISSUE TITLE
test-cris-3

### ISSUE THREAD

**Issue by csmartinsfct** [MyBitFoundation/MyBit-Go.website#168]
Test!

**Comment by csmartinsfct** [comment]
comment

**Comment by csmartinsfct** [comment]
comment

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x4dfdbc97c6e4bf5d458970678cab633b9f58cb069d4d7799fc9240486c02d050](https://etherscan.io/tx/0x4dfdbc97c6e4bf5d458970678cab633b9f58cb069d4d7799fc9240486c02d050)
