### ISSUE TITLE
Trust - possibility of reminder to login to metamask

### ISSUE THREAD

**Issue by rd123myb** [MyBitFoundation/MyBit-Go.website#177]
could be good is to put a reminder up for those who forget to login into metamask before clicking ‘create new’ (like with GO), otherwise the page just freezes without saying what the problem is

**Comment by jjperezaguinaga** [comment]
@rd123myb On which particular product are you referring to? The website does not require login to metamask ☺️

**Comment by rd123myb** [comment]
@jjperezaguinaga sorry about putting things in the wrong category new to github! :). As for the particular product i was referring to the trust dApp (trust.mybit.io) and how a reminder popup for people who click 'create new' without logging in to metamask before hand could be good because at the moment it freezes without saying why if you're not logged in (just a suggestion)

**Comment by jjperezaguinaga** [comment]
@rd123myb no worries and not your fault! Updated the issue [here](https://github.com/MyBitFoundation/MyBit-Trust.website/issues/1). In the future we will provide links to all our project in our website.
