### ISSUE TITLE
About us page for mybit.io

### ISSUE THREAD

**Issue by rd123myb** [MyBitFoundation/MyBit-Go.website#178]
The about us page title 'about us' has no spacer inbetween the title and the paragraph which is inconsistent with other parts of website

**Comment by jjperezaguinaga** [comment]
@rd123myb true! However, this is the repository for the https://go.mybit.io website. Probably you were looking for https://github.com/MyBitFoundation/MyBit.website. However, I went ahead and already replicated your issue there in [here](https://github.com/MyBitFoundation/MyBit.website/issues/23). Thank you!
