### ISSUE TITLE
Link on the Onboading page doesnot work when i try to open it in New tab

### ISSUE THREAD

**Issue by BlueFoxx** [MyBitFoundation/MyBit-Go.website#184]
On the last onboarding page ( https://app.mybit.io/onboarding ) before getting started and explore
![image](https://user-images.githubusercontent.com/45783062/50132136-a9491600-0296-11e9-9f76-a68bbafc3453.png)**
The link provided for "Get Ether" and "Get MYB" is wrong ( https://app.mybit.io/bankor ) it leads to an error page when I try to right click and open in new tab
![image](https://user-images.githubusercontent.com/45783062/50132460-4e182300-0298-11e9-9914-300fb367270b.png)

- It should be able to load metamask even when I open in new tab
- I think using "bancor" on the link address should be better than "Bankor" to avoid alarming users into thinking that it's a phishing attempt

**Comment by jjperezaguinaga** [comment]
@Jerometash thank you! Adding this to our task manager ☺️ 
https://public.3.basecamp.com/p/Y6mCWpFhryePjVZsfAJYUYHR
