### ISSUE TITLE
Lay-out on 3440 X 1440 screen

### ISSUE THREAD

**Issue by michaelvandensteen** [MyBitFoundation/MyBit-Go.website#194]
Hello, 
Like you guys asked, I'm providing feedback using Github now.
The new GO website banner doesn't look very good on a 3440 x 1440 resolution (stretched) + button "View asset" in the banner isn't very readable.

Like the website btw!!
![banner](https://user-images.githubusercontent.com/42436486/57146066-c2c1a900-6dc4-11e9-9c5f-1bd65ec09337.PNG)

**Comment by jjperezaguinaga** [comment]
@michaelvandensteen fun! That's an extreme use case. @csmartinsfct any ideas on this one? We can probably have a max-width for the banner to avoid this.
